<?php

namespace Application\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BonusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonusRepository extends EntityRepository
{

    public function findAll()
    {
        return $this->findBy(array(), array('id' => 'ASC'));
    }

}
