<div class="row"> 
	<div class="col-lg-12">
		<h1>My Profile</h1>
	</div>
</div>

<div class="row"> 
	<div class="col-lg-3">
		<?php echo $this->navigation('navigation')->menu()->setUlClass('nav')->render(); ?>
	</div>
	<div class="col-lg-9">
		profile content

		<?php 
			$form = $this->form;
			$form->prepare();
			echo $this->form()->openTag($form);
		?>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('name')); ?>
			<div class="col-sm-10"><?php echo $this->formInput($form->get('name')); ?></div>
		</div>

		<div class="form-group">
			<?php echo $this->formLabel($form->get('surname')); ?>
			<div class="col-sm-10"><?php echo $this->formInput($form->get('surname')); ?></div>
		</div>

		<div class="form-group">
			<?php echo $this->formLabel($form->get('email')); ?>
			<div class="col-sm-10"><?php echo $this->formInput($form->get('email')); ?></div>
		</div>

		<div class="form-group">
			<div class="col-md-6 col-md-offset-2"><?php echo $this->formRow($form->get('submit')); ?></div>
		</div>


		<?php echo $this->form()->closeTag($form); ?>

		<?php var_dump($player); ?>
	</div>
</div>