Application\Entity\Currency:
  repositoryClass: Application\Repository\CurrencyRepository
  table: currency
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
#  oneToOne:
#    wallet:
#      targetEntity: Application\Entity\Wallet
#      inversedBy: currency
#      joinColumn:
#        name: wallet_id
#        referencedColumnName: id