Application\Entity\Game:
  repositoryClass: Application\Repository\GameRepository
  type: entity
  table: game
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255