Application\Entity\Player:
  repositoryClass: Application\Repository\PlayerRepository
  type: entity
  table: player
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    username:
      type: string
      length: 128
    password:
      type: string
      length: 32
    email:
      type: string
      length: 255
    name:
      type: string
      length: 255
    surname:
      type: string
      length: 255
    age:
      type: smallint
      length: 2
    gender:
      type: smallint
      length: 2
    created_at:
      type: datetime
    updated_at:
      type: datetime  
  indexes:
    search_idx:
      columns: username
  oneToMany:
    wallets:
      targetEntity: Application\Entity\Wallet
      mappedBy: player
  oneToMany:
    logins:
      targetEntity: Application\Entity\Login
      mappedBy: player