<div class="row"> 
	<div class="col-lg-12">
		<h1>Bonuses</h1>
	</div>
</div>

<div class="row"> 
	<div class="col-lg-3">
		<?php echo $this->navigation('navigation')->menu()->setUlClass('nav')->render(); ?>
	</div>

	<div class="col-lg-9">
		<h3>Available Bonuses:</h3>
		<table class="table">
			<?php foreach ($bonuses as $bonus): ?>
				<tr>
					<td><?php echo $bonus->getId() ?></td>
					<td><?php echo $bonus->getName() ?></td>
				</tr>
			<?php endforeach; ?>
		</table>

		<h3>Available Bonuses:</h3>

	</div>
</div>